services:
#  mysql:
#    image: mysql:latest
#    container_name: mysql_latest
#    restart: always
#    command: --mysql-native-password=ON #指定身份验证插件(验证用户身份和原理访问权限的模块)
#    #可以将主机上的文件或目录挂载到容器中，
#    #MySQL容器启动时，会自动执行/docker-entrypoint-initdb.d目录下所有.sql, .sh和.sql.gz文件。
#    volumes:
#      - ./script/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - "13306:3306" #"13306:3306" 表示将主机上的端口 13306 映射到容器内的端口 3306

  redis:
   image: redis:latest
   container_name: redis
   restart: always
   ports:
     - "6379:6379"

  Etcd:
    image: bitnami/etcd:latest
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      # 客户端通信接口
      - 2379:2379
      # 集群节点通信接口
      - 2380:2380

  prometheus:
    image: bitnami/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
    ports:
      - "9090:9090"

#  jaeger:
#    image: jaegertracing/all-in-one:latest
#    container_name: jaeger
#    restart: always
#    ports:
#      - "16686:16686" #Jaeger的查询界面通常运行在这个端口，通过localhost:16686访问JaegerUI
#      - "14268" #这个端口是Jaeger用于接收OpenTelemetry数据的端口
#      - "14250" #这个端口用于接受 gRPC 格式的追踪数据
#    environment:
#      - LOG_LEVEL=debug
