scrape_configs:
  - job_name: prometheus_test
    scrape_interval: 10s
    static_configs:
      - targets:
          - 172.30.144.1:20090
          - 172.30.144.1:20091
          - 172.30.144.1:20092